#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

// don't remove the `+ 32`
// otherwise your sprite will not be placed in the place you desire
#define MUGSHOT_X 168 + 32
#define MUGSHOT_Y 51  + 32

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_MARIBEL,
    MUGSHOT_RENKO,
    MUGSHOT_BIRCH,
    MUGSHOT_WALLY,
    MUGSHOT_ROXANNE,
    MUGSHOT_BRAWLY,
    MUGSHOT_WATTSON,
    MUGSHOT_FLANNERY,
    MUGSHOT_NORMAN,
    MUGSHOT_WINONA,
    MUGSHOT_TATE_LIZA,
    MUGSHOT_JUAN,
    MUGSHOT_SIDNEY,
    MUGSHOT_PHOEBE,
    MUGSHOT_GLACIA,
    MUGSHOT_DRAKE,
    MUGSHOT_WALLACE,
    MUGSHOT_STEVEN,
    MUGSHOT_SHELLY,
    MUGSHOT_MATT,
    MUGSHOT_TABITHA,
    MUGSHOT_COURTNEY,
    MUGSHOT_ARCHIE,
    MUGSHOT_MAXIE,
    MUGSHOT_NOLAND,
    MUGSHOT_GRETA,
    MUGSHOT_TUCKER,
    MUGSHOT_LUCY,
    MUGSHOT_SPENSER,
    MUGSHOT_BRANDON,
    MUGSHOT_ANABEL,
    MUGSHOT_SCOTT,
    MUGSHOT_MIKU,
    MUGSHOT_AICHI,
    MUGSHOT_YUKAI,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_ALT,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
