LandofGensokyo_HakureiShrine_MapScripts::
	.byte 0

LandofGensokyoHakureiShrine_EventScript_MoriyaShrineSign::
	msgbox LandofGensokyoHakureiShrine_Text_MoriyaShrineSign, MSGBOX_SIGN
	end
	
LandofGensokyoHakureiShrine_EventScript_HakureiShrineSign::
	msgbox LandofGensokyoHakureiShrine_Text_HakureiShrineSign, MSGBOX_SIGN
	end
	
LandofGensokyoHakureiShrine_Text_MoriyaShrineSign:
	.string "Moriya Branch Shrine$"
	
LandofGensokyoHakureiShrine_Text_HakureiShrineSign:
	.string "Hakurei Shrine ahead.$"
