gText_Birch_Disclaimer::
	.string "{COLOR GREEN}{SHADOW LIGHT_GRAY}If you got this hack as a pre-patched\n"
	.string "ROM, then please read the following.\p"
	.string "Websites that distribute hacks as\n"
    .string "pre-patched ROMs are best avoided\l"
	.string "for legal and security reasons.\p"
	.string "The Revised hacks have a thread on\n"
	.string "PokéCommunity with documentation, so\l"
	.string "please download it from there instead!\p"
	.string "Anyway, on to Birch.\n"
	.string "-Nyomu and team\p"
	.string "$"

gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Puppets!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Puppet\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Puppet.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Recently, this world is inhabited by\n"
	.string "creatures known as Puppets.\p"
	.string "These Puppets are very mysterious,\n"
	.string "as no one is sure of their origins.\p"
	.string "How did they come to our world?\n"
	.string "And how many of them are there?\p"
	.string "Rumor has it that all Puppets came\n"
	.string "from a world called Gensokyo.\p"
	.string "My goal is to solve the incident\n"
	.string "regarding Puppets and Gensokyo.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Tomboyish or Girlish?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own {COLOR RED}{SHADOW LIGHT_GRAY}Mind-Breaking{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} adventure\n"
	.string "adventure is about to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Puppets where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Puppet Lab.\p"
	.string "$"
