gBirchDexRatingText_AreYouCurious::
	.string "Prof. Birch: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "iDollDex is coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "Bonéka to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} Bonéka,\n"
	.string "and you've caught {STR_VAR_2} Bonéka…$"

gBirchDexRatingText_LessThan10::
	.string "Go into grassy areas more and look\n"
	.string "for Bonéka more carefully.$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some Bonéka only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "an iDollDex now.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any Rods?\n"
	.string "There are many Bonéka in the sea.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching Bonéka,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic\n"
	.string "iDollDex.\l"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the Safari Zone?\p"
	.string "I hear there are some Bonéka that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive iDollDex!$"

gBirchDexRatingText_LessThan120::
	.string "There might be Bonéka that can be\n"
	.string "found using Rock Smash.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more Bonéka\n"
	.string "by trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of Bonéka that evolve\n"
	.string "when they come to fully love their\l"
	.string "Trainers.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many Bonéka species in the Hoenn\l"
	.string "region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some Bonéka appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the Bonéka of the Hoenn region\l"
	.string "by looking through your iDollDex.$"

gBirchDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a Bonéka Professor, and a good\l"
	.string "one, too!$"

gBirchDexRatingText_LessThan190::
	.string "With a iDollDex this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this iDollDex.\l"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your iDollDex is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} Bonéka,\n"
	.string "and you've caught {STR_VAR_2} Bonéka…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "Oak: Good to see you!\n"
	.string "How is your iDollDex coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your iDollDex is:\p"
	.string "{STR_VAR_1} Bonéka seen and\n"
	.string "{STR_VAR_2} Bonéka owned.\p"
	.string "{FONT_NORMAL}Prof. Oak's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for Bonéka!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my Aides a Flash\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your iDollDex could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "Bonéka!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my Aides an\n"
	.string "Itemfinder. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your iDollDex is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my Aides an\n"
	.string "Amulet Coin. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my Aides an Exp.\n"
	.string "Share. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable iDollDex!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "Bonéka by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of Bonéka! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the Bonéka Professor now!$"

PokedexRating_Text_Complete::
	.string "Your iDollDex is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your National iDollDex is:\p"
	.string "{STR_VAR_1} Bonéka seen and\n"
	.string "{STR_VAR_2} Bonéka owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the National iDollDex!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "iDollDex!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your iDollDex\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
