Route103_HouseOfMemories_MapScripts::
	.byte 0

Route103_HouseOfMemories_EventScript_MystiaMan::
	msgbox Route103_HouseOfMemories_Text_MystiaMan, MSGBOX_NPC
	end
	
Route103_HouseofMemories_EventScript_EyesOverflowWoman::
	msgbox Route103_HouseOfMemories_Text_EyesOverflowWoman, MSGBOX_NPC
	end
	
Route103_HouseofMemories_EventScript_AppreciateGentleman::
	msgbox Route103_HouseOfMemories_Text_AppreciateGentleman, MSGBOX_NPC
	end
	
Route103_HouseofMemories_EventScript_RespectPuppetWoman::
	msgbox Route103_HouseOfMemories_Text_RespectPuppetWoman, MSGBOX_NPC
	end
	
Route103_HouseofMemories_EventScript_MtPyreMan::
	msgbox Route103_HouseOfMemories_Text_MtPyreMan, MSGBOX_NPC
	end
	
Route103_HouseOfMemories_Text_MystiaMan:
	.string "This is the final resting place of my\n"
	.string "darling little Mystia…\p"
	.string "I miss her sweet little song…$"
	
Route103_HouseOfMemories_Text_EyesOverflowWoman:
	.string "My eyes overflow thinking…\n"
	.string "thinking of the journey my little\l"
	.string "darling and I were going to take…$"
	
Route103_HouseOfMemories_Text_AppreciateGentleman:
	.string "They say we don't fully appreciate\n"
	.string "What we have until it's gone.\p"
	.string "Even our Puppets can hold so much\n"
	.string "meaning…$"
	
Route103_HouseOfMemories_Text_RespectPuppetWoman:
	.string "Did you come to pay your respects\n"
	.string "to the spirits of departed Puppets?\p"
	.string "You must care for your Puppets a lot.$"
	
Route103_HouseOfMemories_Text_MtPyreMan:
	.string "Ah, welcome…\p"
	.string "I take it you are here to pay your\n"
	.string "respects to the Puppets that lay\l"
	.string "at peace?\p"
	.string "This home was established as a final\n"
	.string "resting place for Puppets who, for one\l"
	.string "reason or another, could not be moved\l"
	.string "to Mt. Pyre.\p"
	.string "Bless your kind-hearted soul, child.$"
