LandofGensokyo_HumanVillage_TrainerHouse1F_MapScripts::
	.byte 0

LandofGensokyoHumanVillageTrainerHouse1F_EventScript_Receptionist::
	msgbox LandofGensokyoHumanVillageTrainerHouse1F_Text_Receptionist, MSGBOX_NPC
	end
	
LandofGensokyoHumanVillageTrainerHouse1F_EventScript_MaleCooltrainer::
	msgbox LandofGensokyoHumanVillageTrainerHouse1F_Text_MaleCooltrainer, MSGBOX_NPC
	end
	
LandofGensokyoHumanVillageTrainerHouse1F_EventScript_Gentleman::
	msgbox LandofGensokyoHumanVillageTrainerHouse1F_Text_Gentleman, MSGBOX_NPC
	end
	
LandofGensokyoHumanVillageTrainerHouse1F_EventScript_FemaleCooltrainer::
	msgbox LandofGensokyoHumanVillageTrainerHouse1F_Text_FemaleCooltrainer, MSGBOX_NPC
	end
	
LandofGensokyoHumanVillageTrainerHouse1F_EventScript_SittingBoy::
	msgbox LandofGensokyoHumanVillageTrainerHouse1F_Text_SittingBoy, MSGBOX_NPC
	end
	
LandofGensokyoHumanVillageTrainerHouse1F_Text_SittingBoy:
	.string "I wonder if they'll be airing interviews\n"
	.string "with tough trainers today?$"
	
LandofGensokyoHumanVillageTrainerHouse1F_Text_FemaleCooltrainer:
	.string "They hold practice battles\n"
	.string "downstairs here.\p"
	.string "I would love to see how well a\n"
	.string "trainer from Hoenn battles.$"
	
LandofGensokyoHumanVillageTrainerHouse1F_Text_Gentleman:
	.string "Whew…\p"
	.string "I need to take a breather after\n"
	.string "some intense battles…\p"
	.string "But even now, I never take a break\n"
	.string "from plotting strategy and combos.$"
	
LandofGensokyoHumanVillageTrainerHouse1F_Text_MaleCooltrainer:
	.string "I'm the best out of all my friends.\n"
	.string "But here…\l"
	.string "I've been useless!$"

LandofGensokyoHumanVillageTrainerHouse1F_Text_Receptionist:
	.string "Welcome to Trainer House, the newest\n"
	.string "and most happening place in Gensokyo.\p"
	.string "We're open to trainers only.\p"
	.string "You can battle against the best\n"
	.string "of the best right downstairs.$"
