Yogyakarta_MapScripts::
	.byte 0

Yogyakarta_EventScript_CitySign::
	msgbox Yogyakarta_Text_CitySign, MSGBOX_SIGN
	end
	
Yogyakarta_EventScript_AichiHouse::
	msgbox Yogyakarta_Text_AichiHouse, MSGBOX_SIGN
	end
	
Yogyakarta_EventScript_OldmanSugiho::
	msgbox Yogyakarta_Text_OldmanSugiho, MSGBOX_SIGN
	end
	
Yogyakarta_EventScript_House1::
	msgbox Yogyakarta_Text_House1, MSGBOX_SIGN
	end
	
Yogyakarta_EventScript_House2::
	msgbox Yogyakarta_Text_House2, MSGBOX_SIGN
	end
	
Yogyakarta_Text_CitySign:
	.string "Yogyakarta\p"
	.string "A peaceful village where\n"
	.string "people and Bonéka thrive.$"
	
Yogyakarta_Text_AichiHouse:
	.string "Aichi and Yukai's home\n"
	.string "Placeholder for JP text$"
	
Yogyakarta_Text_OldmanSugiho:
	.string "Oldman Sugiho\n"
	.string "The World Merchant\p"
	.string "Buy all your needs here!$"
	
Yogyakarta_Text_House1:
	.string "Base Camp$"
	
Yogyakarta_Text_House2:
	.string "Eatherna & Sheffyne's house$"
