Surabaya_MapScripts::
	.byte 0

Surabaya_EventScript_CitySign::
	msgbox Surabaya_Text_CitySign, MSGBOX_SIGN
	end

Surabaya_EventScript_PowerPlantSign::
	msgbox Surabaya_Text_PowerPlantSign, MSGBOX_SIGN
	end

Surabaya_EventScript_JavaHospitalSign::
	msgbox Surabaya_Text_JavaHospitalSign, MSGBOX_SIGN
	end

Surabaya_EventScript_GrandLeagueSign::
	msgbox Surabaya_Text_GrandLeagueSign, MSGBOX_SIGN
	end

Surabaya_EventScript_AncientPyramidSign::
	msgbox Surabaya_Text_AncientPyramidSign, MSGBOX_SIGN
	end

Surabaya_EventScript_MuseumSign::
	msgbox Surabaya_Text_MuseumSign, MSGBOX_SIGN
	end

Surabaya_EventScript_GrassyGardensSign::
	msgbox Surabaya_Text_GrassyGardensSign, MSGBOX_SIGN
	end

Surabaya_EventScript_TrainerMeetSign::
	msgbox Surabaya_Text_TrainerMeetupSign, MSGBOX_SIGN
	end

Surabaya_EventScript_HexKurumi::
	msgbox Surabaya_Text_HexKurumi, MSGBOX_NPC
	end

Surabaya_EventScript_GrandLeagueGuard::
	msgbox Surabaya_Text_LeagueGuard, MSGBOX_NPC
	end

Surabaya_Text_GrandLeagueSign:
	.string "Aim to be the best Bonéka trainer!\n"
	.string "{COLOR RED}{SHADOW LIGHT_RED}The Java Grand League$"

Surabaya_Text_JavaHospitalSign:
	.string "“Cure your illness.”\n"
	.string "Java Hospital$"

Surabaya_Text_AncientPyramidSign:
	.string "Ancient Pyramid\n"
	.string "Still under investigation$"

Surabaya_Text_MuseumSign:
	.string "Surabaya Museum$"

Surabaya_Text_GrassyGardensSign:
	.string "Surabaya City Grassy Garden$"

Surabaya_Text_TrainerMeetupSign:
	.string "Trainer Meetup$"

Surabaya_Text_HexKurumi:
	.string "I wonder if I can catch my\n"
	.string "lovely EKurumi here.\p"
	.string "I haven't encountered any EKurumi\n"
	.string "yet.$"

Surabaya_Text_LeagueGuard:
	.string "The Grand League is rather big,\n"
	.string "isn't it?\p"
	.string "I hear it's very tough to defeat\n"
	.string "every trainer in there,\l"
	.string "but I'll try!\p"
	.string "You should try it out too!$"

Surabaya_Text_CitySign:
	.string "Surabaya City\p"
	.string "The well-developed city of\n"
	.string "eastern Java.$"

Surabaya_Text_PowerPlantSign:
	.string "Surabaya City Power Plant$"