LandofGensokyo_BorderIslandExterior_MapScripts::
	.byte 0

LandofGensokyoBorderIslandExterior_EventScript_Sign::
	msgbox LandofGensokyoBorderIslandExterior_Text_Sign, MSGBOX_SIGN
	end
	
LandofGensokyoBorderIslandExterior_Text_Sign:
	.string "The writing is fading as if it was\n"
	.string "written a long time ago…\p"
	.string "“ber, 6th day\n"
	.string "If any human…sets foot here…\l"
	.string "again… et it be a kindhearted pers…\l"
	.string "… ith that hope, I depar…”$"
