NorthPlain_MapScripts::
	.byte 0

NorthPlain_EventScript_PojokCliffHintKid::
	msgbox NorthPlain_PojokCliffHintKid, MSGBOX_NPC
	end
	
NorthPlain_PojokCliffHintKid:
	.string "Have you heard?\p"
	.string "There's a rumor going around about\n"
	.string "some strange flower field beyond\l"
	.string "Pojok Cliff.\p"
	.string "They say you need a special stone\n"
	.string "to even see that flower field.\p"
	.string "But hey, you can't believe\n"
	.string "everything you hear.$"
