LandofGensokyo_HumanVillage_MapScripts::
	.byte 0

LandofGensokyoHumanVillage_EventScript_HumanVillageSign::
	msgbox LandofGensokyoHumanVillage_Text_HumanVillageSign, MSGBOX_SIGN
	end
	
LandofGensokyoHumanVillage_EventScript_HiedaMansionSign::
	msgbox LandofGensokyoHumanVillage_Text_HiedaMansionSign, MSGBOX_SIGN
	end
	
LandofGensokyoHumanVillage_Text_HumanVillageSign:
	.string "Human Village\n"
	.string "Where humans reside together.$"

LandofGensokyoHumanVillage_Text_HiedaMansionSign:
	.string "Hieda Mansion$"
